version: '3.8'  # Specify the version of Docker Compose

services:
  postgres:
    image: postgres:latest  # Use the latest version of the PostgreSQL image
    container_name: postgres_container1  # Name of the container
    environment:
      POSTGRES_USER: raihan       # Replace with your desired username
      POSTGRES_PASSWORD: raihan   # Replace with your desired password
      POSTGRES_DB: test_db         # Replace with your desired database name
    ports:
      - "5432:5432"  # Expose the PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data

volumes:
  postgres_data:
    driver: local

